/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flipt.api.resources.rollouts.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flipt.api.core.ObjectMappers;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = RolloutListRequest.Builder.class)
public final class RolloutListRequest {
    private final Optional<Integer> limit;

    private final Optional<Integer> offset;

    private final Optional<String> pageToken;

    private final Optional<String> reference;

    private RolloutListRequest(
            Optional<Integer> limit, Optional<Integer> offset, Optional<String> pageToken, Optional<String> reference) {
        this.limit = limit;
        this.offset = offset;
        this.pageToken = pageToken;
        this.reference = reference;
    }

    @JsonProperty("limit")
    public Optional<Integer> getLimit() {
        return limit;
    }

    @JsonProperty("offset")
    public Optional<Integer> getOffset() {
        return offset;
    }

    @JsonProperty("pageToken")
    public Optional<String> getPageToken() {
        return pageToken;
    }

    @JsonProperty("reference")
    public Optional<String> getReference() {
        return reference;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RolloutListRequest && equalTo((RolloutListRequest) other);
    }

    private boolean equalTo(RolloutListRequest other) {
        return limit.equals(other.limit)
                && offset.equals(other.offset)
                && pageToken.equals(other.pageToken)
                && reference.equals(other.reference);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.limit, this.offset, this.pageToken, this.reference);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> limit = Optional.empty();

        private Optional<Integer> offset = Optional.empty();

        private Optional<String> pageToken = Optional.empty();

        private Optional<String> reference = Optional.empty();

        private Builder() {}

        public Builder from(RolloutListRequest other) {
            limit(other.getLimit());
            offset(other.getOffset());
            pageToken(other.getPageToken());
            reference(other.getReference());
            return this;
        }

        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Integer limit) {
            this.limit = Optional.of(limit);
            return this;
        }

        @JsonSetter(value = "offset", nulls = Nulls.SKIP)
        public Builder offset(Optional<Integer> offset) {
            this.offset = offset;
            return this;
        }

        public Builder offset(Integer offset) {
            this.offset = Optional.of(offset);
            return this;
        }

        @JsonSetter(value = "pageToken", nulls = Nulls.SKIP)
        public Builder pageToken(Optional<String> pageToken) {
            this.pageToken = pageToken;
            return this;
        }

        public Builder pageToken(String pageToken) {
            this.pageToken = Optional.of(pageToken);
            return this;
        }

        @JsonSetter(value = "reference", nulls = Nulls.SKIP)
        public Builder reference(Optional<String> reference) {
            this.reference = reference;
            return this;
        }

        public Builder reference(String reference) {
            this.reference = Optional.of(reference);
            return this;
        }

        public RolloutListRequest build() {
            return new RolloutListRequest(limit, offset, pageToken, reference);
        }
    }
}
