/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flipt.api.resources.auth.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flipt.api.core.ObjectMappers;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = AuthenticationToken.Builder.class)
public final class AuthenticationToken {
    private final String clientToken;

    private final Authentication authentication;

    private AuthenticationToken(String clientToken, Authentication authentication) {
        this.clientToken = clientToken;
        this.authentication = authentication;
    }

    @JsonProperty("clientToken")
    public String getClientToken() {
        return clientToken;
    }

    @JsonProperty("authentication")
    public Authentication getAuthentication() {
        return authentication;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AuthenticationToken && equalTo((AuthenticationToken) other);
    }

    private boolean equalTo(AuthenticationToken other) {
        return clientToken.equals(other.clientToken) && authentication.equals(other.authentication);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.clientToken, this.authentication);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ClientTokenStage builder() {
        return new Builder();
    }

    public interface ClientTokenStage {
        AuthenticationStage clientToken(String clientToken);

        Builder from(AuthenticationToken other);
    }

    public interface AuthenticationStage {
        _FinalStage authentication(Authentication authentication);
    }

    public interface _FinalStage {
        AuthenticationToken build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ClientTokenStage, AuthenticationStage, _FinalStage {
        private String clientToken;

        private Authentication authentication;

        private Builder() {}

        @Override
        public Builder from(AuthenticationToken other) {
            clientToken(other.getClientToken());
            authentication(other.getAuthentication());
            return this;
        }

        @Override
        @JsonSetter("clientToken")
        public AuthenticationStage clientToken(String clientToken) {
            this.clientToken = clientToken;
            return this;
        }

        @Override
        @JsonSetter("authentication")
        public _FinalStage authentication(Authentication authentication) {
            this.authentication = authentication;
            return this;
        }

        @Override
        public AuthenticationToken build() {
            return new AuthenticationToken(clientToken, authentication);
        }
    }
}
