/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flipt.api.resources.auth.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum AuthenticationMethod {
    METHOD_NONE("METHOD_NONE"),

    METHOD_TOKEN("METHOD_TOKEN"),

    METHOD_OIDC("METHOD_OIDC"),

    METHOD_KUBERNETES("METHOD_KUBERNETES"),

    METHOD_JWT("METHOD_JWT");

    private final String value;

    AuthenticationMethod(String value) {
        this.value = value;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
